### ISSUE TITLE
Exception on ParseArticleAsync due to missing lock

### ISSUE THREAD

**Issue by theolivenbaum** [Strumenta/SmartReader#20]
There is an issue when using this library from multiple threads, due to a missing lock on this line:

https://github.com/Strumenta/SmartReader/blob/2cd5e7fb7e5d79e98ccc452afe98280c8e435eaf/src/SmartReader/SmartReader.cs#L169

```
 System.ArgumentException: An item with the same key has already been added. Key: System.Net.Http.Headers.HeaderDescriptor
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at System.Net.Http.Headers.HttpHeaderValueCollection`1.ParseAdd(String input)
   at SmartReader.Reader..ctor()
   at SmartReader.Reader..ctor(String uri)
   at SmartReader.Reader.ParseArticleAsync(String uri)
```

@ftomassetti If you want I can send a pull request, but in any case should be a quite simple change - just missing a lock object and locking on it before the check on the constructor....

**Comment by gabriele-tomassetti** [comment]
Thanks for noticing this bug. If you have the time, I would appreciate a pull request, otherwise I would get to it next week.

Honestly, I never thought about this aspect. Do you see any other issue to make the library thread-safe?
