### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'SocketsHttpHandler'. 

### ISSUE THREAD

**Issue by MaratPavlov** [Strumenta/SmartReader#22]
.NET Core 3.1 
Smart Reader 0.7.3

`foreach(var url in urls){
   var tmpArticle = Reader.ParseArticle(url);
   ....
}`

The first iteration is successful, and the second has an error 
"System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SocketsHttpHandler'.
   at System.Net.Http.SocketsHttpHandler.CheckDisposed()
   at System.Net.Http.SocketsHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at SmartReader.Reader.GetStreamAsync(Uri resource)
   at SmartReader.Reader.ParseArticle(String uri, String userAgent)

**Comment by gabriele-tomassetti** [comment]
Thanks for the bug report. I will look into it.

**Comment by MaratPavlov** [comment]
There is in asp.net core, not in console app. You can try it in the Controller:
`
 Reader.ParseArticle("https://blabla.com");
 Reader.ParseArticle("https://blabla.com"); // throws an error
`

**Comment by gabriele-tomassetti** [comment]
I found the reason for the bug. You are not [supposed to dispose HttpClient](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) unless you use a setting to not dispose the inner handler. However, given what is said [here](http://www.michaeltaylorp3.net/httpclient-is-it-really-thread-safe/) I am starting think that the underlying issue is that probably we should not allow to change user agent if the static methods are used.

For now, I will release a new version to fix this bug. Let me know if the new version 0.7.4 will fix this for you. It will take a while to appear on nuget.

**Comment by MaratPavlov** [comment]
Yes, your fix helped, thank you!
