### ISSUE TITLE
 SmartReader.UriExtensions.ToAbsoluteURI(Uri pageUri, String uriToCheck) throws exception when uriToCheck = ""

### ISSUE THREAD

**Issue by mininmaxim** [Strumenta/SmartReader#41]
SmartReader.UriExtensions.ToAbsoluteURI(Uri pageUri, String uriToCheck) throws exception when uriToCheck = ""

Stack trace:
   at System.String.get_Chars(Int32 index)
   at SmartReader.UriExtensions.ToAbsoluteURI(Uri pageUri, String uriToCheck) in D:\work\tmp\SmartReader-master\SmartReader-master\src\SmartReader\UriExtensions.cs:line 46
   at SmartReader.Readability.FixRelativeUris(IElement articleContent, Uri uri, IHtmlDocument doc) in D:\work\tmp\SmartReader-master\SmartReader-master\src\SmartReader\Readability.cs:line 121
   at SmartReader.Reader.PostProcessContent(IElement articleContent) in D:\work\tmp\SmartReader-master\SmartReader-master\src\SmartReader\SmartReader.cs:line 413
   at SmartReader.Reader.Parse() in D:\work\tmp\SmartReader-master\SmartReader-master\src\SmartReader\SmartReader.cs:line 1914
   at SmartReader.Reader.GetArticle() in D:\work\tmp\SmartReader-master\SmartReader-master\src\SmartReader\SmartReader.cs:line 337
   at SmartReaderConsole.Program.Main(String[] args) in D:\work\tmp\SmartReader-master\SmartReader-master\src\SmartReaderConsole\Program.cs:line 123

![image](https://user-images.githubusercontent.com/20446176/171856285-17615458-4b19-4415-a62a-845cc148f181.png)

**Comment by gabriele-tomassetti** [comment]
Thanks for the bug report. I wonder how that slipped through until now. I will work on a fix in the next few days.
