### ISSUE TITLE
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.

### ISSUE THREAD

**Issue by iansmirlis** [Strumenta/SmartReader#55]
Hello

I have a few cases with the below exception

```
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at SmartReader.Readability.GetArticleMetadata(IHtmlDocument doc, Uri uri, String language, Dictionary`2 jsonLD)
   at SmartReader.Reader.Parse()
   at SmartReader.Reader.GetArticle()
```

Example URLs:
http://lefteria.blogspot.com/2023/01/66.html
http://old-boy.blogspot.com/2011/07/32-27.html

**Comment by gabriele-tomassetti** [comment]
Thanks for the clear bug report. I will probably fix it this weekend.
